# NumPy Arrays

In [2]:
my_list = [1,2,3]

In [3]:
import numpy as np

In [8]:
arr = np.array(my_list) # casting list as an array

In [9]:
arr

array([1, 2, 3])

In [10]:
my_mat = [[1,2,3],[4,5,6],[8,7,9]]

In [11]:
my_mat

[[1, 2, 3], [4, 5, 6], [8, 7, 9]]

In [13]:
np.array(my_mat)  # this is a two dimensional array

array([[1, 2, 3],
       [4, 5, 6],
       [8, 7, 9]])

In [16]:
np.arange(0,11,2) 

array([ 0,  2,  4,  6,  8, 10])

In [17]:
np.zeros(3)

array([0., 0., 0.])

In [23]:
np.zeros((5,5))  # 5 x 5 dimension

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [24]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [28]:
np.linspace(0,5,10)  # 10 evenly spaced points till 5

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [32]:
np.eye(4)  # identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [42]:
np.random.rand(5)  # returns 5 uniformly (equally likely) numbers (0 to 1) in a one demensional array

array([0.27239117, 0.49524453, 0.44475846, 0.73028926, 0.09021554])

In [43]:
np.random.rand(5,5)  # random two dimensional array

array([[0.84446507, 0.51680285, 0.80494059, 0.02404309, 0.19908725],
       [0.57704202, 0.43285368, 0.81240852, 0.26778918, 0.96121414],
       [0.19988767, 0.90797635, 0.79858713, 0.86295958, 0.85134467],
       [0.75902424, 0.07131752, 0.1996346 , 0.64165486, 0.970323  ],
       [0.27313073, 0.19270904, 0.72011083, 0.48806422, 0.55152826]])

In [47]:
np.random.randn(2,2)

array([[-1.89106207, -0.47828735],
       [-0.60328726,  0.88919195]])

In [51]:
np.random.randint(1,100,(5,5))

array([[84, 72, 55,  9, 24],
       [79, 25, 83, 11, 44],
       [83, 20,  8, 66, 52],
       [51, 55, 12, 93, 76],
       [15, 44, 92, 88, 48]])

In [52]:
arr = np.arange(25)

In [53]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [54]:
ranarr = np.random.randint(0,50,10)

In [55]:
ranarr

array([22, 14, 14, 26, 35, 34, 49, 26, 10, 46])

In [68]:
arr.reshape(5,5)  # reshape inputs must multiply to equal size

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [69]:
ranarr.max()

49

In [79]:
ranarr.min()

10

In [71]:
ranarr.argmax()  # returns index at which max value is located

6

In [72]:
ranarr.argmin()

8

In [73]:
arr = arr.reshape(5,5)

In [74]:
arr.shape

(5, 5)

In [75]:
ranarr.argmax()

6

In [77]:
arr.dtype  # shows datatype in array (32 bit integers)

dtype('int32')

# Lesson Review:

-----------------------------------------

np.array(*list*) : casts list as an array

np.arange(start:stop:step) : returns an array w/evenly spaced values in interval

----------------------------------------------------------------------------------------

np.zeros(row,column) : generates array of zeros

np.ones(row,column) : generates array of ones

np.linspace(start,stop,num) : return evenly space nums on specified interval

np.eyes(num) : creates indentity matrix

----------------------------------------------------------------------------------------

np.random.rand(row,column) : array is created with uniformly distributed numbers from 0 to 1 from the specified shape

np.random.randn(row,column) : standardly distributes unlike rand which is uniform

np.random.randint(start,stop,(row,column)): generates an array with random nums withing specified interval

----------------------------------------------------------------------------------------

*array*.reshape(row,column) : returns an array with same data with a new shape

*array*.max()/min() : returns max/min num in array

*array*.argmax()/argmin() : returns index at which max/min is located

*array*.shape : returns shape of array

*array*.dtype(): returns data type in array