In [2]:
import numpy as np

In [2]:
my_matrix = [[1,2,3], [4,5,6], [7,8,9]]

In [5]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
np.shape(my_matrix)

(3, 3)

In [14]:
np.reshape(my_matrix,(3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
np.arange(1,11,1).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [30]:
np.ones((4,4), dtype = bool)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

**`Full`**

In [32]:
np.full((3,5), "3")

array([['3', '3', '3', '3', '3'],
       ['3', '3', '3', '3', '3'],
       ['3', '3', '3', '3', '3']], dtype='<U1')

**`Linspace`**

In [34]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [35]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [38]:
np.linspace(0,10)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [45]:
np.random.randint(0,500,(50,10))

array([[123, 256,  21,  17,  87, 392, 228,  67, 229, 425],
       [210, 323, 234, 348, 268, 310,  47, 143,  36, 305],
       [448,  26, 119, 334, 247, 319, 115, 395, 319, 466],
       [247, 155, 209, 194, 273, 239, 458, 147, 284,  72],
       [ 51, 251, 408, 465, 368, 272, 224,  13,  45, 101],
       [233, 150, 337,   9,  45, 247, 339,  87,  72, 490],
       [ 43,  91,  39, 246,  16,  11, 193, 228, 476, 421],
       [ 33, 324, 451, 191, 262,  25, 189, 468, 143, 409],
       [ 86, 147, 240, 118, 479, 344, 488, 142, 476, 342],
       [412, 419, 304,  66, 276, 442, 227, 314, 242, 271],
       [158,   9, 166,  53, 369, 425, 228, 196, 356, 484],
       [409, 350,  25,   5, 462, 256, 150, 335, 271, 447],
       [446,  41, 492, 299, 410,  32, 227, 305, 486, 131],
       [ 69, 326, 199, 336, 439, 313, 119, 444, 441, 449],
       [438,  84, 439, 424, 160,  55, 297, 329, 139, 221],
       [186,  25, 289, 326, 437, 220, 337, 328,  59, 331],
       [379, 389, 439,   0, 317, 161, 355, 160,   5,  64

In [17]:
np.random.randint(1,[3, 50, 100], size = (5, 3))

array([[ 2, 35, 31],
       [ 2, 15, 11],
       [ 1, 44, 29],
       [ 1,  5, 98],
       [ 2, 25, 29]])

In [30]:
m = np.arange(20).reshape(5,4)

In [31]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [32]:
np.vsplit(m, [1,3])  # splits array into vertical sub arrays

[array([[0, 1, 2, 3]]),
 array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19]])]

**2d Matrix**

In [35]:
twoD = np.random.randint(5,100,(3,3))

twoD

array([[98, 44, 83],
       [35, 57, 98],
       [ 7, 33,  9]])

In [37]:
np.sort(twoD, axis = 1)

array([[44, 83, 98],
       [35, 57, 98],
       [ 7,  9, 33]])

In [40]:
np.sort(twoD, axis = 0)

array([[ 7, 33,  9],
       [35, 44, 83],
       [98, 57, 98]])